spring:
  application:
    name: Demo JWT
  datasource:
    url: jdbc:postgresql://localhost:5432/DB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    driverClassName: org.postgresql.Driver
    platform: postgres
    initialization-mode: always
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
       
