spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      datasource: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-plataform: org.hibernate.dialect.PostgreSQLDialect